name: motiondet
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - ipykernel
  - requests
  - jupyterlab
  - notebook
  - ipywidgets
  - opencv
  - pyyaml
  - scipy

  - pip:
      - addict
      - folium
      - geopandas>=0.14.0
      - imagesize
      - jupyterlab-widgets
      - moviepy
      - networkx>=3.0
      - onnx
      - onnxruntime
      - opencv-python
      - osmnx
      - pathspec
      - pykitti>=0.3.1
      - pyproj>=3.6.0
      - python-dotenv
      - rich
      - shapely>=2.0.0
      - tensorboard
      - torch
      - torchaudio
      - torchmetrics
      - torchvision
      - ujson
      - ultralytics==8.2.35
      - wandb
