name: motiondet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - ipykernel
  - requests
  - jupyterlab
  - notebook
  - ipywidgets
  - opencv
  - pyyaml
  - scipy
  - pip:
      - ultralytics==8.2.35
      - onnx
      - onnxruntime
      - osmnx
      - folium
      - moviepy
      - rich
      - torchmetrics
      - wandb
      - python-dotenv
      - jupyterlab-widgets
      - torch
      - torchvision
      - torchaudio
      - pykitti>=0.3.1
      - pyproj>=3.6.0
      - networkx>=3.0
      - geopandas>=0.14.0
      - shapely>=2.0.0