name: motiondet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pillow
  - requests
  - jupyterlab
  - notebook
  - ipywidgets
  - opencv
  - torch
  - torchvision
  - torchaudio
  - pip:
      - ultralytics==8.2.35
      - onnx
      - onnxruntime
      - onnxruntime-gpu
      - tensorrt
      - osmnx
      - folium
      - moviepy
      - pycuda
      - rich
      - torchmetrics
      - wandb
      - python-dotenv
      - jupyterlab-widgets
